### ISSUE TITLE
startup crash after newest update

### ISSUE THREAD

**Issue by freopt** [Seniorendi/AdvancedPeripherals#256] opened 2022-01-20 01:38 UTC
### Descripe

Game crashes on startup after updating to 0.7.7r, rolling back fixes

### Steps to reproduce

launch game

### Multiplayer?

No

### Version

0.7.7r

### Minecraft, Forge and maybe other related mods versions

forge 36.2.23 mc 1.16.5

### Crashlog/log

https://gist.github.com/freopt/acf205df64f4ea5ac2b9418f6e25def5

**Comment by SirEndii** [comment] 2022-01-20 01:44
Can't reproduce this in my dev environment, but I'll make more tests tomorrow. 
For now, I'll go sleep *It's really late in germany :P*
But thank you for the report

**Comment by Diversion98** [comment] 2022-01-20 14:49
Same issue having here, 0.7.6r works just fine

issue: advancedperipherals-1.16.5-0.7.7r.jar has mods that were not found
crash report: https://paste.ee/p/LXkFz
latest log: https://paste.ee/p/qLLsi

**Comment by KydZombie** [comment] 2022-01-20 18:18
Also having this issue while putting together a new pack

**Comment by SirEndii** [comment] 2022-01-21 12:24
Fixed in 0.7.7.1r

**Closed as completed by SirEndii** 2022-01-21 12:24 UTC
Labels: bug, 1.16x, Priority-High

**Comment by Diversion98** [comment] 2022-01-21 19:33
I saw u uploaded 0.7.7.1r but it has the fabric tag and not the forge tag :p

**Comment by SirEndii** [comment] 2022-01-21 20:28
Damn
Thank you for the hint
