### ISSUE TITLE
Items do not stack

### ISSUE THREAD

**Issue by Leialoha** [Seniorendi/AdvancedPeripherals#502] opened 2023-08-14 07:36 UTC
### Describe

Whenever using the Inventory Manager, any items placed into a container (like a barrel) the item gets `{tag:{}}` added to it's NBT. This make it so new crafted items do no stack with items taken out of the barrel (unless the item is sent to the barrel).

### Steps to reproduce

1. Use peripheral `inventoryManager`
2. Get the item from the players inventory using `manager.getItems()`
3. Set the items "fromSlot" nbt to the item's slot
4. Use `manager.removeItemFromPlayerNBT()`

You can use my script from [here](https://gist.github.com/Leialoha/f699233e8ab062d5368fc0173393c8d9) to test this out.

### Multiplayer?

Yes

### Version

1.18.2-0.7.31r (Latest 1.18.2)

### Minecraft, Forge and maybe other related mods versions

Forge 40.2.4 Minecraft 1.18.2

**Comment by SirEndii** [comment] 2023-11-12 02:31
I at least can't reproduce this in 1.18, maybe I fixed it accidentally
I will close this, feel free to re-open the issue if you are still able to reproduce this

**Closed as completed by SirEndii** 2023-11-12 02:31 UTC
Labels: bug, Priority-Medium, 1.18x
