### ISSUE TITLE
suggestion: keyboard

### ISSUE THREAD

**Issue by awesomebossdj7** [Seniorendi/AdvancedPeripherals#364] opened 2022-11-09 12:00 UTC
### Describe your idea

I was recently playing with some cc mods in 1.7.10, I had a mod "moar peripherals". It has a block that when you right click, it basically functions like you were typing on the computer but you aren't in the computer GUI. Kind of uses the same type of code from the pocket computer when you are typing with it.

### Additional context

would be awesome if this could become a feature, if its even possible.

**Comment by SirEndii** [comment] 2022-11-09 13:49
Duplicate of https://github.com/Seniorendi/AdvancedPeripherals/issues/31

**Closed as completed by SirEndii** 2022-11-09 13:49 UTC
