### ISSUE TITLE
Colony Integrator Error

### ISSUE THREAD

**Issue by Glitched-Fox-Studios** [Seniorendi/AdvancedPeripherals#311] opened 2022-07-01 05:37 UTC
### Descripe

When attempting to use any script that include the getRequests() function, a null pointer error regarding citizenData is thrown.

<img width="930" alt="image" src="https://user-images.githubusercontent.com/75238752/176830556-d583720c-7273-4d19-9507-2eecab6d240b.png">

Version is 15b

### Steps to reproduce

Code for getRequests
Run script
See error

### Multiplayer?

Yes

### Version

1.18.2-0.7.14b (Latest 1.18)

### Minecraft, Forge and maybe other related mods versions

Forge 40.1.47 Minecraft 1.18.2

### Crashlog/log

https://pastebin.com/L1MnDb68

**Comment by SirEndii** [comment] 2022-07-01 05:47
duplicate of #310

**Closed as completed by SirEndii** 2022-07-01 05:47 UTC
