### ISSUE TITLE
Hidden message kicking all players on Aternos server

### ISSUE THREAD

**Issue by blockninja124** [Seniorendi/AdvancedPeripherals#553] opened 2024-01-26 17:11 UTC
### Describe

I'm not sure if this is a bug everywhere, but I encountered it on an Aternos server. When sending a hidden message, the next message sent by anyone in chat causes the server to kick everyone for "chat message validation failure". (Not consistently, but often)

I did find that with the message '$007' it was caused pretty often

Also I'm using Advanced Peripherals 1.19.2-0.7.32r but I couldn't find it on the version selector.

![image](https://github.com/IntelligenceModding/AdvancedPeripherals/assets/64211894/0acfbf71-7d41-451c-a646-6f13b46eb21d)

### Steps to reproduce

0.5. Do this on an Aternos server?
1. Send the message $007 (or something else)
2. Send any other message (not hidden)
3. Repeat till kicked from server

### Multiplayer?

Yes

### Version

Own compiled build.

### Minecraft, Forge and maybe other related mods versions

Forge 43.3.0 Minecraft 1.19.2

### Crashlog/log

Server log doesn't mention anything other than 'player disconnected'

**Comment by SirEndii** [comment] 2024-01-26 21:21
Is that a cracked or online server?

**Comment by zyxkad** [comment] 2024-01-26 21:23
In fact I've met this problem before, I was on a mixed online server, exactly same reproduce. However, I forgot how did we solved that :(

**Comment by zyxkad** [comment] 2024-01-26 21:24
@blockninja124 Can you give the mod list?

**Comment by blockninja124** [comment] 2024-01-27 19:53
It’s not a cracked server, everyone on it has bought Minecraft, which makes the bug even stranger. 

Mod list:
Cc:tweaked 1.101.3
DB extended 5.1
Supplementaries 2.4.15
Adv peripherals 0.7.32r
Auto reg lib 1.8.2-55
Cc:c bridge 1.5.1
Chipped 2.1.5
CTM 1.1.6+8
Create 0.5.1f
Create deco 1.3.3
Create modern train parts 0.2.2
Create steam n rails 1.5.3
Framed blocks 6.8.6
Framework 0.6.16
Geckolib 3.1.40
Journeymap 5.9.7
Moonlight lib 2.3.6
Not enough crashes 5.0.0
Quark 3.4-418
Quark oddities 1.18
ReAuth 4.0.7
Resourceful lib 1.1.24
Rubidium 0.6.2c

**Comment by SirEndii** [comment] 2024-01-30 21:09
@zyxkad @blockninja124 
Can you try to use this version?
https://mvn.intelligence-modding.de/Intelligence/de/srendi/advancedperipherals/advancedperipherals-snapshots/1.19.2-0.7.32r-SNAPSHOT-192/advancedperipherals-snapshots-1.19.2-0.7.32r-SNAPSHOT-192.jar

I am playing around fixing the issue by trying to cancel the message as early as I can to prevent race conditions from other mods.

**Comment by Leialoha** [comment] 2024-02-01 18:23
This is ~~an issue~~ a feature with players ~~connecting~~ chatting with an "insecure" account, one that doesn't have a key for encrypting chat messages. You can disable this in the **server.properties** by changing `enforce-secure-profile=true` to `enforce-secure-profile=false` or download an [anti encrypt mod](https://modrinth.com/mod/no-chat-reports).

**Comment by blockninja124** [comment] 2024-02-02 08:54
But why would my normal Minecraft account not have a key for encryption? Shouldn't that just be provided? @SirEndii I think I'm unable to have a mod on the Aternos server that isn't on Curseforge (for safety reasons). Perhaps someone else with an actual server can test it? In the meantime, I'll try what Leialoha said with the config, see if that fixes anything. If it works, perhaps advanced peripherals can force that setting by default or something? (If that's something that's possible, I'm not a modder)

**Comment by blockninja124** [comment] 2024-02-02 10:48
I have tested and can confirm: Change enforce-secure-profile does not stop the bug, however an anti-encrypt mod (I used 'no chat reports') did seem to stop the bug entirely. Not sure what this means for a more permanent fix, but it does provide a nice temporary solution.

**Comment by SirEndii** [comment] 2024-02-09 13:09
I will close this as completed
Maybe I fixed it with the higher priority, but that's a thing I can't really test since the bug seems to occur randomly.

If someone is able to reproduce this with the newest, feel free to re-open the issue

**Closed as completed by SirEndii** 2024-02-09 13:09 UTC
Labels: bug, waiting for feedback, 1.19x, 1.20.1
