### ISSUE TITLE
New inventory items not stacking after inventory is processed by Inventory Manager

### ISSUE THREAD

**Issue by OneTwoMint** [Seniorendi/AdvancedPeripherals#199] opened 2021-09-14 03:03 UTC
### Descripe

It's happened in a lot of circumstances over the course of my survival worlds, but a fairly simple example is this one: After smelting some gold ingots, I perform a process that involves running the Inventory Manager's `getItems()` function. Later, I smelt more gold ingots, and place them in my inventory, only to find that they don't stack with the ones I already have. Similarly, gold ingots from generated chests don't stack with the ones I have. I can throw the two stacks of ingots out of my inventory, and they will be able to stack when Minecraft combines the stacks to reduce the number of item entities, but I will probably still encounter this issue later with the same stack.

I've mostly observed this bug in multiplayer, but that's because I mostly play in multiplayer. You can replicate the bug in singleplayer, and I have.

### Steps to reproduce

1. Create a new world.
2. Place a furnace, a computer, and an inventory manager with a memory card linked to you.
3. Smelt some ore.
4. Run `getItems()` from the Inventory Manager somehow, easiest way is to just wrap it as a peripheral in the lua application of the computer and execute it directly from there. such as with an Inventory Manager on the right:
`x = peripheral.wrap("right")`
`x.getItems()`
5. Smelt more ore.
6. Observe that the new ore does not stack with the old ore

### Multiplayer?

Yes

### Version

0.7.1r (Latest)

### Minecraft, Forge and maybe other related mods versions

Forge 36.2.0 MC 1.16.5

### Screenshots or Videos

https://youtu.be/4UNefvMY7rs

### Crashlog/log

https://gist.github.com/OneTwoMint/c2f1d8affa8aaa4d61381493cba10b98

**Comment by SirEndii** [comment] 2021-09-14 08:29
Duplicate of #177

**Closed as completed by SirEndii** 2021-09-14 08:29 UTC
