### ISSUE TITLE
Create Crafts & Additions power connectors break energy detectors (1.18.2)

### ISSUE THREAD

**Issue by GalacticArc** [Seniorendi/AdvancedPeripherals#536] opened 2023-11-20 02:11 UTC
### Describe

When connecting the "Connectors" from create crafts & additions mod onto the energy detector, it completely breaks, and stops transferring until broken and replaced.

### Steps to reproduce

**Get the following mods:**
Create Crafts & Additions 1.0.0 (createaddition-1.18.2-1.0.0.jar)
CC:Tweaked (cc-tweaked-1.18.2-1.101.3.jar)
Advanced peripherals (AdvancedPeripherals-1.18.2-0.7.31r.jar)
Thermal Expansion (thermal_dynamics-1.18.2-9.2.2.19.jar + all addons)

Step 1: set up a circuit that has power throughput
Step 2: Put energy detector in between
Step 3: Use Create Crafts & Additions power connectors to transfer power (createaddition:large_connector)
Step 4: Notice energy does not transfer
Step 5: Replace connectors with Redstone energy cells from thermal expansion
Step 6: Notice energy will no longer transmit via detector

Extra notes:
They work fine with the mod installed if you put Thermal Expansion cells

### Multiplayer?

Yes

### Version

Own compiled build.

### Minecraft, Forge and maybe other related mods versions

Forge 40.2.13 Minecraft 1.18.2

**Comment by rytt0001** [comment] 2024-03-02 13:15
I can also reproduce it on MC 1.19.2 / Forge 43.3.5 when using large connector in these steps:
- place energy detector
- place large connector on input and connect it to the generator side
- place any connector on the output side and link to an empty battery
- The current will NOT pass through until you break the energy detector and replace it at the same spot

**Comment by Einhornyordle** [comment] 2024-03-08 18:26
I just tried to reproduce this bug with the latest version of AP, CC:Tweaked, Create, Create Crafts & Additions and Mekanism (instead of Thermal Expansion since I'm more familiar with it) in MC Version 1.18.2, 1.19.2 and 1.20.1 and I couldn't. Are you sure it's a bug and not a user error?

![image](https://github.com/IntelligenceModding/AdvancedPeripherals/assets/47315090/024a63a5-cee9-4a8b-8057-73d3eb66b4f6)
I've used this simple setup from left to right: Full energy Cube -> Large Connector -> Electrum Spool -> Large Connector -> Energy Detector (w/ Advanced Computer) -> Large Connector -> Electrum Spool -> Large Connector -> Empty Energy Cube.
The Placement Order is Cubes -> Advanced Computer -> Energy Detector -> Connectors -> Spools.

Did you make sure to check that the input and output side of the Energy Detector are correctly placed? The energy detector only has one input and one output side and those are fixed on the opposite sides of the block and specially marked so you can see which side is which.
Also, did you use the Create Wrench on the Large Connectors to configure them correctly to either take energy (from the energy source and the energy detector output) or push energy (to the energy detector input and the energy sink)? Some of them already had the right configuration on placement but I had to reconfigure some manually.

**Comment by rytt0001** [comment] 2024-03-08 18:46
I Tried and here is my setup: 
https://drive.google.com/file/d/1Wa1L01ePz0z9pQzZFYLhU3yXZvqWX7J8/view?usp=sharing
(sorry Video too big, needed to use drive)
You can see as I break the output connector (the one attached to the energy detector) and place it again ( with or without changing mode before linking it with a cable)
the accumulator does not charge anymore, and the tooltip on the top right says that the energy output is 0FE/t

Versions : 
Craft and additions 1.19.2-1.2.3
AdvancedPeripherals 1.19.2-0.7.32r (apparently the server I played on crashed with the upper vervions on the modpack we used but  not related, maybe) Also tested in latest 1.19.2-07.34r
CC:Tweaked 1.19.2-1.101.4
Maybe Related :
CC:C bridge 1.19.2-v1.5.1

**Comment by Einhornyordle** [comment] 2024-03-08 19:13
Ah, I see what you mean and I can reproduce that. Thanks for the clarification

**Closed as completed** 2024-04-15 21:08 UTC
Labels: bug, Priority-Low, Fixed/Added in dev, 1.19x, 1.20.1
