### ISSUE TITLE
Colony Integrator Error

### ISSUE THREAD

**Issue by Glitched-Fox-Studios** [Seniorendi/AdvancedPeripherals#310] opened 2022-07-01 05:34 UTC
### Descripe

When trying to use getRequest(), e NullPointer Exception is thrown. This is on 15b.

<img width="930" alt="image" src="https://user-images.githubusercontent.com/75238752/176829219-a5eec327-9730-4926-b931-208f43bd098b.png">

### Steps to reproduce

Create code using getRequest()
Run Code
Read Error.

### Multiplayer?

Yes

### Version

1.18.2-0.7.14b (Latest 1.18)

### Minecraft, Forge and maybe other related mods versions

Forge 40.1.47 Minecraft 1.18.2

### Screenshots or Videos

See above

### Crashlog/log

https://pastebin.com/L1MnDb68

**Comment by SirEndii** [comment] 2022-07-01 05:37
oh boy
I love minecolonies

**Comment by Glitched-Fox-Studios** [comment] 2022-07-02 19:21
Providing an update here. This error seems to be getting caused if ANY hut has a minimum stock set. Removing minimum stock from all huts removes this error and allows the block to work.

**Comment by SirEndii** [comment] 2022-07-02 22:15
thank you, this helps me a lot

**Comment by Glitched-Fox-Studios** [comment] 2022-07-06 03:36
Further note. This same error also occurs if you use the Postbox to request something.

**Comment by LittleWoglug** [comment] 2022-07-06 18:17
Also seeing this error, But it only started today not been able to connect it to postbox or min stock though

**Comment by SirEndii** [comment] 2022-07-06 22:54
[advancedperipherals-1.18.2-0.7.15b.zip](https://github.com/Seniorendi/AdvancedPeripherals/files/9059049/advancedperipherals-1.18.2-0.7.15b.zip)

Hey, could you try it again with this version? It will probably not work, but I need the new generated (crash)log
Unzip the file before using

**Comment by LittleWoglug** [comment] 2022-07-07 18:31
Still getting the same error with your edited file

Error from latest.log
https://pastebin.com/EJY46wV5

**Comment by SirEndii** [comment] 2022-07-07 19:29
[advancedperipherals-1.18.2-0.7.15b.zip](https://github.com/Seniorendi/AdvancedPeripherals/files/9066810/advancedperipherals-1.18.2-0.7.15b.zip)
I now know what the issue is. And I think I got it fixed.
Free to test 😉

**Comment by LittleWoglug** [comment] 2022-07-07 21:16
The exception looks to be fixed, but now getting an error in my Lua

error:
`attempt to index global 'target' (a nil value)`

Lua snippet:
```
local colony = peripheral.find("colonyIntegrator")

workRequests = colony.getRequests()

for w in pairs(workRequests) do

        target = workRequests[w].target

        for word in target:gmatch("%S+") do  --This line
            table.insert(target_words, word)
            target_length = target_length + 1
        end
end
```

**Comment by SirEndii** [comment] 2022-07-07 23:02
This is an issue at the end of minecolonies. I contacted them and I now wait for an answer

Explanation
The exception throws when the requester of a request is not a citizen - like a restaurant
I'll send more updates about this in the next days. In the meanwhile, target will be nil if the requester is not a citizen

**Comment by LittleWoglug** [comment] 2022-07-08 20:19
Soo. I just found out. One of the other players had set some min stock levels in the restaurant. I removed them and it fixed the nil error.

So I agree with your diagnosis. It looks to be min stock requests (i.e. non citizen requests) that are causing this

**Comment by SirEndii** [comment] 2022-07-15 12:10
Fixed in 
https://github.com/ldtteam/minecolonies/pull/8501
Do you want to test it with 1.18.2-0.7.15b?

**Comment by Glitched-Fox-Studios** [comment] 2022-07-16 01:53
Just to be certain, which mine colonies version?

**Comment by SirEndii** [comment] 2022-07-16 07:12
https://www.curseforge.com/minecraft/mc-mods/minecolonies/files/3876528

**Comment by Glitched-Fox-Studios** [comment] 2022-07-16 11:01
That link is for 1.16.5 and I don't see that change being listed in any of the 1.18.2 files.

**Comment by Gobgob30** [comment] 2022-07-16 18:51
https://www.curseforge.com/minecraft/mc-mods/minecolonies/files/3876507
Worked for me!

**Comment by SirEndii** [comment] 2022-07-16 21:03
> That link is for 1.16.5 and I don't see that change being listed in any of the 1.18.2 files.

Yeah, 1.18.2-1.0.883-ALPHA contains the fix. The changelog only shows the newest commit.

**Comment by SirEndii** [comment] 2022-07-16 21:03
I'll close this now since it's an issue with minecolonies which got fixed

**Closed as completed by SirEndii** 2022-07-16 21:03 UTC
Labels: bug, not AdvancedPeripherals, Fixed/Added in dev, 1.18x
