### ISSUE TITLE
[Feature]  Inventory Manager .getItems()/.list() function also returns slots

### ISSUE THREAD

**Issue by Cyakat** [Seniorendi/AdvancedPeripherals#192] opened 2021-09-05 23:25 UTC
### Describe your idea

The block reader is able to get the slot of an item and it is very useful when using with the inventory manager. It would be nice if the inventory manager could also return the slot that an item is in so that the item that I want to removed can be specified.

### Additional context

I would like this feature because I have designed a system that allows me to transfer items from my home storage to my inventory using a portable computer and a server at my base. I have a GUI setup where I can click on the item I want and it can send it to me. However, I wanted to be able to send items too but the inventory manager doesn't tell me which slots are the items are in so I can't use the .removeItemFromPlayer() and have it specify an item.

**Comment by SirEdvin** [comment] 2021-09-06 09:05
This is seems like duplicate of SirEndii/Advanced-Peripherals-Features#49, closing

**Closed as completed by SirEdvin** 2021-09-06 09:05 UTC
Labels: duplicate
