### ISSUE TITLE
NullPointer whenn calling isItemCrafting

### ISSUE THREAD

**Issue by mcenderdragon** [Seniorendi/AdvancedPeripherals#171] opened 2021-08-16 15:51 UTC
### Descripe

when calling isItemCRafting a nUllPointerException occurs.

```
java.lang.NullPointerException: null
        at de.srendi.advancedperipherals.common.addons.refinedstorage.RefinedStorage.getItems(RefinedStorage.java:182) ~[advancedperipherals:0.6r] {re:classloading}
        at de.srendi.advancedperipherals.common.addons.refinedstorage.RefinedStorage.listItems(RefinedStorage.java:74) ~[advancedperipherals:0.6r] {re:classloading}
        at de.srendi.advancedperipherals.common.addons.computercraft.peripheral.RsBridgePeripheral.listItems(RsBridgePeripheral.java:55) ~[advancedperipherals:0.6r] {re:classloading}
        at de.srendi.advancedperipherals.common.addons.computercraft.peripheral.RsBridgePeripheral$cc$listItems118.apply(CC generated method) ~[?:?] {re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading}
        at dan200.computercraft.shared.peripheral.modem.wired.WiredModemPeripheral$RemotePeripheralWrapper.callMethod(WiredModemPeripheral.java:350) ~[computercraft:1.97.0] {re:clas
```

### Steps to reproduce

wrap a RsBridge
call isCraftable

### Version

0.6r

### Minecraft, Forge and maybe other related mods versions

36.1.32

### Screenshots or Videos

-

### Crashlog/log

-

**Comment by SirEndii** [comment] 2021-08-16 16:14
Duplicate of https://github.com/Seniorendi/AdvancedPeripherals/issues/166

**Closed as completed by SirEndii** 2021-08-16 16:14 UTC
Labels: bug, duplicate, 1.16x

**Comment by mcenderdragon** [comment] 2021-08-17 09:52
But a conncurent modification exception is something entierly different - it happens becuase if threading this will always happen even when no import/export is going on.

**Comment by mcenderdragon** [comment] 2021-08-17 09:55
ohh I see, intern this is also just calling listCraftableItems and then fails.
