### ISSUE TITLE
Server Crash calling meBridge.getAvailableFluidStorage()

### ISSUE THREAD

**Issue by CodeLeopard** [Seniorendi/AdvancedPeripherals#478] opened 2023-06-28 16:18 UTC
### Describe

When calling `meBridge.getAvailableFluidStorage()` the server crashes. 

Happens both on a server and in singleplayer
The included log is from singleplayer where I reproduced the issue.
I have requested the multiplayer server log, but due to time zones don't have a response yet.

### Steps to reproduce

Setup a trivial ME network: I used a ME drive with any storage cell inside (kind does not matter). A power source is not required. Attach a meBridge to the drive, and a computer to the bridge.

On the computer open a lua prompt and enter:
`peripheral.find('meBridge').getAvailableFluidStorage()`
The server will crash.

### Multiplayer?

Yes

### Version

1.19.2-0.7.28r

### Minecraft, Forge and maybe other related mods versions

Minecraft: 1.19.2, Forge: 43.2.14

### Crashlog/log

https://pastebin.com/bMxGR0Tw (0.7.28r)
https://pastebin.com/uZu5CZ9R (0.7.27r)

**Comment by SirEndii** [comment] 2023-06-29 15:45
This bug should be fixed in the newest AP Version (1.19.3-0.7.29r)

**Comment by CodeLeopard** [comment] 2023-06-29 18:25
Would it be possible to fix it also for minecraft 1.19.2 ?
I looked into updating to 1.19.3 but many mods in the pack don't have a version that supports it and break.

**Comment by SirEndii** [comment] 2023-06-29 18:34
Why did you select 1.19.3 if you play on 1.19.2?
The newest 1.19.2 should also have this fix, but I can quick check that for you

**Comment by CodeLeopard** [comment] 2023-06-29 18:38
Oh sorry looks like I selected the wrong version. I really thought I double checked it too 🥴.
I'll look through the issue again now to make sure everything is correct.

**Comment by CodeLeopard** [comment] 2023-06-29 18:44
I just retested with `1.19.2-0.7.28r` and get crash, the stack trace also appears the same at a quick glance. I updated the main post to reflect the version numbers of this test.

**Comment by SirEndii** [comment] 2023-06-29 18:57
So the issue is that if you don't have [ae2things](https://www.curseforge.com/minecraft/mc-mods/ae2-things-forge/files) installed, the function will lead to a crash

Could you try this version? Unzip the file before using it

[AdvancedPeripherals-1.19.2-0.7.28r.zip](https://github.com/SirEndii/AdvancedPeripherals/files/11909559/AdvancedPeripherals-1.19.2-0.7.28r.zip)

**Comment by CodeLeopard** [comment] 2023-06-29 19:02
It works 🎉 
That was fast, thanks!

Edit: I didn't install ae2things yet but it works anyway.

**Comment by SirEndii** [comment] 2023-06-30 14:28
Fixed in 1.19.2-0.7.29r

**Closed as completed by SirEndii** 2023-06-30 14:28 UTC
Labels: bug, Priority-High, Fixed/Added in dev, 1.19x
