### ISSUE TITLE
[Issue] Chat stops working for all server members.

### ISSUE THREAD

**Issue by JJSax** [Seniorendi/AdvancedPeripherals#96] opened 2021-06-06 19:41 UTC
**Describe**
Chat gets disabled for entire server.  Everyone's chat settings are one shown.  We can still use commands, including /say, but the chat box doesn't register chat event.  Disabling this mod fixes the issue.  This started happening before anybody crafted a chat box.  When we type a message in chat, nothing happens, we can't even see our own chat message.

Note: This was fixed in beta version 0.6.5b, but I'm not certain if this was intentionally fixed or not.  Just making you and anyone with this issue aware of it.

**Reproduce**
This is difficult to reproduce as nobody on the server has any idea of what happened right before this issue started.   We just went to the nether sometime around when this issue started.  That's the closest notable thing we could think about.  I also posted a journeymap link once successfully then after that it stopped. This was the first time I noticed it.

...

**Versions:**

- Forge version: 36.1.18
- AdvancedPeripherals version: 0.6r

**Crashlog/log (Use https://paste.gg or https://pastebin.com to upload your crashlog/log)**
https://pastebin.com/gA1Vt8hj

**Comment by Seniorendi** [comment] 2021-06-06 19:45
> Note: This was fixed in beta version 0.6.5b, but I'm not certain if this was intentionally fixed or not. Just making you and anyone with this issue aware of it.

It isn't fixed in 0.6.5b, but you can try this version if you want.
[advancedperipherals-0.6.6b.zip](https://github.com/Seniorendi/AdvancedPeripherals/files/6604809/advancedperipherals-0.6.6b.zip)
Unzip the file before using.

This is also a duplicate of #82

**Closed by Seniorendi** 2021-06-06 19:45 UTC

**Comment by jkmmo** [comment] 2021-06-19 13:47
the issue is still there even in the zip you linked.

**Comment by Seniorendi** [comment] 2021-06-19 17:12
It should be fixed in 0.6.7b
I already tested it, it does not seem to happen again.
Could you send a log?

**Comment by jkmmo** [comment] 2021-06-19 18:43
[20:35:58] [Server thread/FATAL] [minecraft/ThreadTaskExecutor]: Error executing task on Server
java.lang.NullPointerException: null
        at de.srendi.advancedperipherals.common.events.Events.lambda$onChatTurtle$1(Events.java:60) ~[advancedperipherals:0.6r] {re:classloading}
        at java.util.ArrayList.forEach(ArrayList.java:1541) ~[?:?] {}
        at de.srendi.advancedperipherals.common.events.Events.onChatTurtle(Events.java:51) ~[advancedperipherals:0.6r] {re:classloading}
        at net.minecraftforge.eventbus.ASMEventHandler_51_Events_onChatTurtle_ServerChatEvent.invoke(.dynamic) ~[?:?] {}
        at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-4.0.0.jar:?] {}
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {}
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {}
        at net.minecraftforge.common.ForgeHooks.onServerChatEvent(ForgeHooks.java:485) ~[forge:?] {re:classloading}
        at net.minecraft.network.play.ServerPlayNetHandler.func_244548_c(ServerPlayNetHandler.java:1105) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:fml:astralsorcery:reach_set_server_entity_interact,xf:fml:astralsorcery:allow_entity_interaction,pl:mixin:A}
        at net.minecraft.network.play.ServerPlayNetHandler.func_244545_b(ServerPlayNetHandler.java:303) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:fml:astralsorcery:reach_set_server_entity_interact,xf:fml:astralsorcery:allow_entity_interaction,pl:mixin:A}
        at net.minecraft.network.play.ServerPlayNetHandler.func_244538_a(ServerPlayNetHandler.java:316) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:fml:astralsorcery:reach_set_server_entity_interact,xf:fml:astralsorcery:allow_entity_interaction,pl:mixin:A}
        at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) ~[?:?] {re:classloading}
        at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) ~[?:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
        at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?] {re:mixin,re:computing_frames,re:classloading}
        at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:734) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixin.terraforged.json:common.MixinMinecraftServer,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:159) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixin.terraforged.json:common.MixinMinecraftServer,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) ~[?:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:717) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixin.terraforged.json:common.MixinMinecraftServer,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:711) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixin.terraforged.json:common.MixinMinecraftServer,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213160_bf(SourceFile:103) ~[?:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:696) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixin.terraforged.json:common.MixinMinecraftServer,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:646) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixin.terraforged.json:common.MixinMinecraftServer,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixin.terraforged.json:common.MixinMinecraftServer,pl:mixin:A,pl:runtimedistcleaner:A}
        at java.lang.Thread.run(Thread.java:829) [?:?] {}

**Comment by Seniorendi** [comment] 2021-06-19 18:58
You use an old version(0.6r). The latest version is 0.6.7b.
