### ISSUE TITLE
CC computer crashes with null pointer exception while server starting 

### ISSUE THREAD

**Issue by 1Euro7Cent** [Seniorendi/AdvancedPeripherals#457] opened 2023-05-13 09:58 UTC
### Describe

The cc computer crashes while having a startup script in /startup/name.lua

the script in particular 

[lager.zip](https://github.com/SirEndii/AdvancedPeripherals/files/11469372/lager.zip)
the function in particular is `getItem()`

when I simply reboot the CC computer it works just fine

### Steps to reproduce

In my case I use an advanced computer

have a Minecraft server 
have the necessary stuff to make it work (me system...)
put the script given in the startup folder of a computer
[lager.zip](https://github.com/SirEndii/AdvancedPeripherals/files/11469372/lager.zip)

reboot the CC computer to see if it works

Reboot the Minecraft server itself.

After reboot look into the CC computer and see the attached error

### Multiplayer?

Yes

### Version

1.19.2-0.7.27r (Latest 1.19.2)

### Minecraft, Forge and maybe other related mods versions

Forge 43.2.0; Minecraft 1.19.2

### Screenshots or Videos

![image](https://github.com/SirEndii/AdvancedPeripherals/assets/67194495/06a2f055-2982-48ed-83f1-ec672db0d945)

**Comment by Patprehn** [comment] 2023-05-17 15:43
Duplicate of #434

**Closed as completed by Patprehn** 2023-05-17 15:43 UTC
Labels: Fixed/Added in dev, 1.18x, 1.19x
