### ISSUE TITLE
Chucky Turtle not chunk load and so stop to work.

### ISSUE THREAD

**Issue by gungun974** [Seniorendi/AdvancedPeripherals#246] opened 2022-01-01 11:57 UTC
### Describe

I found that in MC 1.18.1 with forge version 39.0.9 that the chunk loader does not work. (The chunks unload when player is away from more than about 400 blocks)

Note: this bug is as well on server.

### Steps to reproduce

1. First create a map (for me i try in a super flat)
2. Create a advanced or basic turtle with in his left a chat box and in his right a chunk loader
3. Write a program that post in tchat every 1s a message that say the turtle is still loaded.
```lua
-- https://pastebin.com/7b81ztFG
local box = peripheral.find("chatBox")
 
i = 0
while true do
  i = i + 1
  box.sendMessage("Hoi " .. i)
  sleep(1)
end
```
4. Run the program and go away
~~5. (Cry cause you found a bug and so you need to stay near the turtle until this bug is fix)~~

### Multiplayer?

Bug is present in single player and on server.

### Version

0.7.8.1r (Latest)

### Minecraft, Forge and maybe other related mods versions

Forge 39.0.9 / Minecraft 1.18.1 (Mods JourneyMap, CC Tweaked and this mod)

### Screenshots or Videos

Bug demo video:
https://drive.google.com/file/d/1SP6CQVQbnE_39ZIP6IqQe6uSH9apJ6tt/view?usp=sharing

**Comment by SirEndii** [comment] 2022-01-01 12:22
Good bug report but
Duplicate of #238

**Closed as completed** 2022-01-01 12:22 UTC

**Comment by gungun974** [comment] 2022-01-01 12:38
Sorry if this is a duplicate of issue #238.

Basically I had already read this issue but since it talks about both server and other mods I told myself that this must be a separate problem.

In any case, I still hope that duplicated issue will have contributed to the solution of this problem by having eliminated the introduction of another mod to the problem and defined a simple way to reproduce the problem.

Had a nice days.

PS: Do you had any idea why this bug occured ?

**Comment by SirEndii** [comment] 2022-01-22 16:57
> In any case, I still hope that duplicated issue will have contributed to the solution of this problem by having eliminated the introduction of another mod to the problem and defined a simple way to reproduce the problem.

Sure it does

> PS: Do you had any idea why this bug occured ?

Currently not, probably forge changed something and we need to change our chunk system a bit

But sorry for the late answer, didn't see your questions
