### ISSUE TITLE
meBridge.listItems() returns 0

### ISSUE THREAD

**Issue by soer7022** [Seniorendi/AdvancedPeripherals#531] opened 2023-10-30 21:14 UTC
### Describe

The following program:
![image](https://github.com/SirEndii/AdvancedPeripherals/assets/17567175/7dd97c5d-a9f2-4db5-a448-036db533d95d)
prints the following:
![image](https://github.com/SirEndii/AdvancedPeripherals/assets/17567175/a2fe77b0-ae30-4c58-b64e-9653e1e4cdd6)
indicating that the me bridge can see that item storage is being used but cant list any items.

### Steps to reproduce

1. Connect meBridge to AE network
2. Run program described
3. See no items returned

### Multiplayer?

Yes

### Version

1.20.1-0.7.32b (Latest 1.20.1)

### Minecraft, Forge and maybe other related mods versions

1.20.1-47.2.0

**Comment by soer7022** [comment] 2023-10-30 21:34
It seems to work in singleplayer but not in multiplayer. Not sure if there's some server settings that need to be set...

I'm admin on the server so can easily change whatever 😄

**Comment by soer7022** [comment] 2023-11-02 09:35
I ended up bypassing this by just doing a `me.getItem()` on every single item I need to get.

**Comment by SirEndii** [comment] 2023-11-02 10:26
Reopened since the bug still exists

**Comment by SirEndii** [comment] 2023-11-09 19:14
> It seems to work in singleplayer but not in multiplayer. Not sure if there's some server settings that need to be set...
> 
> I'm admin on the server so can easily change whatever 😄

Hey, since you're admin, could you enable the debug mode of Advanced Peripherals(config/Advancedperipherals/general.toml -> enableDebugMode) and send me the part of the log when you try to run the function?

**Comment by SirEndii** [comment] 2023-11-12 04:24
I am gonna close this since I am unable to reproduce this on my end
Feel free to reopen the issue if you are able to reproduce this somehow

**Closed as completed by SirEndii** 2023-11-12 04:24 UTC
Labels: bug, Priority-Low, Can't reproduce
